src/Entity/Discipline.php
<?php

namespace App\Entity;

use App\Repository\DisciplineRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;

#[ORM\Entity(repositoryClass: DisciplineRepository::class)]
class Discipline implements \JsonSerializable
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[Groups(['participation'])]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(['participation'])]
    private ?string $titre = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Groups(['participation'])]
    private ?string $slug = null;

    #[ORM\OneToMany(mappedBy: 'discipline', targetEntity: Competir::class)]
    #[Groups(['participation'])]
    private Collection $competirs;

    #[ORM\Column(nullable: true)]
    private ?int $joueur = null;

    #[ORM\ManyToMany(targetEntity: Abonnement::class, mappedBy: 'disciplines')]
    private Collection $abonnements;

    #[ORM\ManyToMany(targetEntity: Joueur::class, mappedBy: 'discipline')]
    private Collection $joueurs;

    #[ORM\Column(nullable: true, options: (['default' => true]))]
    private ?bool $Complementaire = null;

    public function __construct()
    {
        $this->competirs = new ArrayCollection();
        $this->abonnements = new ArrayCollection();
        $this->joueurs = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(?string $titre): static
    {
        $this->titre = $titre;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(?string $slug): static
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @return Collection<int, Competir>
     */
    public function getCompetirs(): Collection
    {
        return $this->competirs;
    }

    public function addCompetir(Competir $competir): static
    {
        if (!$this->competirs->contains($competir)) {
            $this->competirs->add($competir);
            $competir->setDiscipline($this);
        }

        return $this;
    }

    public function removeCompetir(Competir $competir): static
    {
        if ($this->competirs->removeElement($competir)) {
            // set the owning side to null (unless already changed)
            if ($competir->getDiscipline() === $this) {
                $competir->setDiscipline(null);
            }
        }

        return $this;
    }

    public function jsonSerialize(): mixed
    {
        return [
            'id' => $this->id,
            'titre' => $this->titre,
            'joueur' => $this->joueur,
            'slug' => $this->slug,
        ];
    }

    public function getJoueur(): ?int
    {
        return $this->joueur;
    }

    public function setJoueur(?int $joueur): static
    {
        $this->joueur = $joueur;

        return $this;
    }

    /**
     * @return Collection<int, Abonnement>
     */
    public function getAbonnements(): Collection
    {
        return $this->abonnements;
    }

    public function addAbonnement(Abonnement $abonnement): static
    {
        if (!$this->abonnements->contains($abonnement)) {
            $this->abonnements->add($abonnement);
            $abonnement->addDiscipline($this);
        }

        return $this;
    }

    public function removeAbonnement(Abonnement $abonnement): static
    {
        if ($this->abonnements->removeElement($abonnement)) {
            $abonnement->removeDiscipline($this);
        }

        return $this;
    }

    /**
     * @return Collection<int, Joueur>
     */
    public function getJoueurs(): Collection
    {
        return $this->joueurs;
    }

    public function addJoueur(Joueur $joueur): static
    {
        if (!$this->joueurs->contains($joueur)) {
            $this->joueurs->add($joueur);
            $joueur->addDiscipline($this);
        }

        return $this;
    }

    public function removeJoueur(Joueur $joueur): static
    {
        if ($this->joueurs->removeElement($joueur)) {
            $joueur->removeDiscipline($this);
        }

        return $this;
    }

    public function isComplementaire(): ?bool
    {
        return $this->Complementaire;
    }

    public function setComplementaire(?bool $Complementaire): static
    {
        $this->Complementaire = $Complementaire;

        return $this;
    }
}

src/Controller/Backend/BackendDisciplineController.php
<?php

namespace App\Controller\Backend;

use App\Entity\Discipline;
use App\Form\DisciplineType;
use App\Repository\DisciplineRepository;
use App\Service\AllRepositories;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/backend/discipline')]
class BackendDisciplineController extends AbstractController
{
    public function __construct(
        private AllRepositories $allRepositories
    )
    {
    }

    #[Route('/', name: 'app_backend_discipline_index', methods: ['GET','POST'])]
    public function index(Request $request, EntityManagerInterface $entityManager, DisciplineRepository $disciplineRepository): Response
    {
        $discipline = new Discipline();
        $form = $this->createForm(DisciplineType::class, $discipline);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->allRepositories->slug($discipline);
            $entityManager->persist($discipline);
            $entityManager->flush();

            sweetalert()->addSuccess("La discipline a été ajoutée avec succès!");

            return $this->redirectToRoute('app_backend_discipline_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('backend_discipline/index.html.twig', [
            'disciplines' => $disciplineRepository->findAll(),
            'discipline' => $discipline,
            'form' => $form,
            'suppression' => false
        ]);
    }

    #[Route('/new', name: 'app_backend_discipline_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $discipline = new Discipline();
        $form = $this->createForm(DisciplineType::class, $discipline);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($discipline);
            $entityManager->flush();

            return $this->redirectToRoute('app_backend_discipline_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('backend_discipline/new.html.twig', [
            'discipline' => $discipline,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_backend_discipline_show', methods: ['GET'])]
    public function show(Discipline $discipline): Response
    {
        return $this->render('backend_discipline/show.html.twig', [
            'discipline' => $discipline,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_backend_discipline_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Discipline $discipline, EntityManagerInterface $entityManager,  DisciplineRepository $disciplineRepository): Response
    {
        $form = $this->createForm(DisciplineType::class, $discipline);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->allRepositories->slug($discipline);
            $entityManager->flush();

            sweetalert()->addSuccess("La discipline {$discipline->getTitre()} a été ajoutée avec succès!");

            return $this->redirectToRoute('app_backend_discipline_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('backend_discipline/edit.html.twig', [
            'disciplines' => $disciplineRepository->findAll(),
            'discipline' => $discipline,
            'form' => $form,
            'suppression' => true
        ]);
    }

    #[Route('/{id}', name: 'app_backend_discipline_delete', methods: ['POST'])]
    public function delete(Request $request, Discipline $discipline, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$discipline->getId(), $request->request->get('_token'))) {
            $entityManager->remove($discipline);
            $entityManager->flush();

            sweetalert()->addSuccess("La discipline {$discipline->getTitre()} a été supprimée avec succès!");
        }

        return $this->redirectToRoute('app_backend_discipline_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/backend_discipline/_delete_form.html.twig
<form method="post" action="{{ path('app_backend_discipline_delete', {'id': discipline.id}) }}" onsubmit="return confirm('Voulez-vous vraiment supprimer cette discipline?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ discipline.id) }}">
    <button class="btn btn-danger">Supprimer</button>
</form>

templates/backend_discipline/_form.html.twig
<div class="modal-dialog">
    <div class="modal-content">
        {{ form_start(form) }}
        <div class="modal-header modal-colored-header bg-primary text-white" >
            <h4 class="modal-title" id="primary-header-modalLabel" > Formulaire</h4>
            <button
                    type="button"
                    class="btn-close"
                    data-bs-dismiss="modal"
                    aria-label="Close"
            ></button>
        </div>
        <div class="modal-body">
            <div class="row form-group">
                <div class="col-12 mb-3">{{ form_row(form.titre) }}</div>
                <div class="col-12 mb-3">{{ form_row(form.joueur) }}</div>
                <div class="col-12 mb-3">
                    <div class="form-check mb-3">
                        {{ form_widget(form.complementaire) }}
                        {{ form_label(form.complementaire) }}
                    </div>
                </div>
            </div>
            {{ form_widget(form) }}
        </div>
        <div class="modal-footer">
            <a href="{{ path('app_backend_discipline_index') }}" class="btn btn-light">
                Annuler
            </a>
            <button type="submit" class="btn btn-light-primary text-primary font-medium" id="saveButton" >
                {{ button_label|default('Enregistrer') }}
            </button>

            {{ form_end(form) }}
            {% if suppression == true %}
                {{ include('backend_discipline/_delete_form.html.twig') }}
            {% endif %}

        </div>
    </div>
</div>

templates/backend_discipline/edit.html.twig
{% extends 'backend_layout.html.twig' %}

{% block title %}{{ parent() }} Gestion des disciplines{% endblock %}

{% block body %}

    <div class="container-fluid">
        <div class="card bg-light-info shadow-none position-relative overflow-hidden">
            <div class="card-body px-4 py-3">
                <div class="row align-items-center">
                    <div class="col-9">
                        <h4 class="fw-semibold mb-8">Gestion des disciplines</h4>
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a class="text-muted" href="#">Modules</a></li>
                                <li class="breadcrumb-item"><a class="text-muted" href="#">Produits</a></li>
                                <li class="breadcrumb-item" aria-current="page">disciplines</li>
                            </ol>
                        </nav>
                    </div>
                    <div class="col-3">
                        <div class="text-center mb-n5">
                            <span class="head-icon"><i class="ti-package"></i></span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <section>
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <div class="row">
                                <div class="col"><h5 class="mb-2 fw-semibold fs-4">Liste</h5></div>
                                <div class="col">
                                    <div class="action">
                                        <button class="btn btn-primary" data-bs-toggle="modal"
                                                data-bs-target="#primary-header-modal"><i class="ti-plus"></i> Ajouter</button>
                                    </div>
                                </div>
                            </div>

                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                <table id="listes" class="table  border table-striped table-bordered display text-nowrap" style="width: 100%;">
                                    <thead>
                                    <tr>
                                        <th class="text-center text-uppercase">#</th>
                                        <th class="text-center text-uppercase">Titre</th>
                                        <th class="text-center text-uppercase">actions</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for discipline in disciplines %}
                                        <tr>
                                            <td>{{ loop.index }}</td>
                                            <td>{{ discipline.titre }}</td>
                                            <td class="text-center">
                                                <a href="{{ path('app_backend_discipline_edit', {'id': discipline.id}) }}"><i class="ti-pencil-alt"></i></a>
                                            </td>
                                        </tr>
                                    {% else %}
                                        <tr>
                                            <td colspan="3">Aucun discipline trouvé</td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </section>

        <div id="primary-header-modal" class="modal fade" tabindex="-1" aria-labelledby="primary-header-modalLabel" aria-hidden="true">
            {{ include('backend_discipline/_form.html.twig', {'button_label': 'Modifier'}) }}
        </div>

    </div>

{% endblock %}
{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ absolute_url(asset('backoffice/vendor/css/prism.min.css')) }}">
    <link rel="stylesheet" href="{{ absolute_url(asset('backoffice/vendor/DataTables/datatables.min.css')) }}">
{% endblock %}
{% block javascripts %}
    {{ parent() }}
    <script src="{{ absolute_url(asset('backoffice/vendor/js/prism.js')) }}"></script>
    <script src="{{ absolute_url(asset('backoffice/vendor/DataTables/datatables.min.js')) }}"></script>
    <script>
        $('#listes').DataTable( {
            dom: 'Bfrtip',
            scrollX: true,
            buttons: [
                'copy', 'excel', 'pdf'
            ]
        } );
    </script>

    <script>
        document.addEventListener("DOMContentLoaded", function() {
            var modal = new bootstrap.Modal(document.getElementById("primary-header-modal"));
            modal.show();
        });
    </script>
{% endblock %}

templates/backend_discipline/index.html.twig
{% extends 'backend_layout.html.twig' %}

{% block title %}{{ parent() }} Gestion des disciplines{% endblock %}

{% block body %}

    <div class="container-fluid">
        <div class="card bg-light-info shadow-none position-relative overflow-hidden">
            <div class="card-body px-4 py-3">
                <div class="row align-items-center">
                    <div class="col-9">
                        <h4 class="fw-semibold mb-8">Gestion des disciplines</h4>
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a class="text-muted" href="#">Modules</a></li>
                                <li class="breadcrumb-item"><a class="text-muted" href="#">Produits</a></li>
                                <li class="breadcrumb-item" aria-current="page">disciplines</li>
                            </ol>
                        </nav>
                    </div>
                    <div class="col-3">
                        <div class="text-center mb-n5">
                            <span class="head-icon"><i class="ti-package"></i></span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <section>
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <div class="row">
                                <div class="col"><h5 class="mb-2 fw-semibold fs-4">Liste</h5></div>
                                <div class="col">
                                    <div class="action">
                                        <button class="btn btn-primary" data-bs-toggle="modal"
                                                data-bs-target="#primary-header-modal"><i class="ti-plus"></i> Ajouter</button>
                                    </div>
                                </div>
                            </div>

                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                <table id="listes" class="table  border table-striped table-bordered display text-nowrap" style="width: 100%;">
                                    <thead>
                                    <tr>
                                        <th class="text-center text-uppercase">#</th>
                                        <th class="text-center text-uppercase">Titres</th>
                                        <th class="text-center text-uppercase">Joueurs</th>
                                        <th class="text-center text-uppercase">Complementaires</th>
                                        <th class="text-center text-uppercase">actions</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for discipline in disciplines %}
                                        <tr>
                                            <td>{{ loop.index }}</td>
                                            <td>{{ discipline.titre }}</td>
                                            <td class="text-center">{{ discipline.joueur }}</td>
                                            <td class="text-center">
                                                {{ discipline.complementaire ? '<span class="badge bg-success">OUI</span>' : '<span class="badge bg-danger">NON</span>'}}
                                            </td>
                                            <td class="text-center">
                                                <a href="{{ path('app_backend_discipline_edit', {'id': discipline.id}) }}"><i class="ti-pencil-alt"></i></a>
                                            </td>
                                        </tr>
                                    {% else %}
                                        <tr>
                                            <td colspan="3">Aucun discipline trouvé</td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </section>

        <div id="primary-header-modal" class="modal fade" tabindex="-1" aria-labelledby="primary-header-modalLabel" aria-hidden="true">
            {{ include('backend_discipline/_form.html.twig') }}
        </div>

    </div>

{% endblock %}
{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ absolute_url(asset('backoffice/vendor/css/prism.min.css')) }}">
    <link rel="stylesheet" href="{{ absolute_url(asset('backoffice/vendor/DataTables/datatables.min.css')) }}">
{% endblock %}
{% block javascripts %}
    {{ parent() }}
    <script src="{{ absolute_url(asset('backoffice/vendor/js/prism.js')) }}"></script>
    <script src="{{ absolute_url(asset('backoffice/vendor/DataTables/datatables.min.js')) }}"></script>
    <script>
        $('#listes').DataTable( {
            dom: 'Bfrtip',
            scrollX: true,
            buttons: [
                'copy', 'excel', 'pdf'
            ]
        } );
    </script>
{% endblock %}

templates/backend_discipline/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Discipline{% endblock %}

{% block body %}
    <h1>Create new Discipline</h1>

    {{ include('backend_discipline/_form.html.twig') }}

    <a href="{{ path('app_backend_discipline_index') }}">back to list</a>
{% endblock %}

templates/backend_discipline/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Discipline{% endblock %}

{% block body %}
    <h1>Discipline</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ discipline.id }}</td>
            </tr>
            <tr>
                <th>Titre</th>
                <td>{{ discipline.titre }}</td>
            </tr>
            <tr>
                <th>Slug</th>
                <td>{{ discipline.slug }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_backend_discipline_index') }}">back to list</a>

    <a href="{{ path('app_backend_discipline_edit', {'id': discipline.id}) }}">edit</a>

    {{ include('backend_discipline/_delete_form.html.twig') }}
{% endblock %}